package com.sunbeam;

public enum EnumMenu {
	EXIT,ADDNEWBOOK,DISPLAYALLBOOKSRANDOMACCESS,SEARCHBOOKBYISBN,DELETEBOOKBYINDEX,DELETEBOOKBYISBN,DELETEBOOKBYNAME,SORTBYISBNASC,SORTBYPRICEDESC,REVERSELIST,SAVEINFILE,LOADFROMFILE,DEFAULT;
}

